// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryContext {
    #[prost(string, optional, tag = "1")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub agent_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub run_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryContent {
    #[prost(string, tag = "1")]
    pub summary: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MemorySignals {
    #[prost(uint32, tag = "1")]
    pub certainty: u32,
    #[prost(uint32, tag = "2")]
    pub salience: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TemporalMetadata {
    #[prost(int64, tag = "1")]
    pub created_at: i64,
    #[prost(int64, optional, tag = "2")]
    pub updated_at: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub archived_at: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtractedMethod {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub prompt: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SummarizedMethod {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProvenanceMethod {
    #[prost(oneof = "provenance_method::Method", tags = "1, 2, 3")]
    pub method: ::core::option::Option<provenance_method::Method>,
}
/// Nested message and enum types in `ProvenanceMethod`.
pub mod provenance_method {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Method {
        #[prost(bool, tag = "1")]
        Direct(bool),
        #[prost(message, tag = "2")]
        Extracted(super::ExtractedMethod),
        #[prost(message, tag = "3")]
        Summarized(super::SummarizedMethod),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Provenance {
    #[prost(enumeration = "ProvenanceOrigin", tag = "1")]
    pub origin: i32,
    #[prost(message, optional, tag = "2")]
    pub method: ::core::option::Option<ProvenanceMethod>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Memory {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub context: ::core::option::Option<MemoryContext>,
    #[prost(enumeration = "LifecycleState", tag = "3")]
    pub lifecycle: i32,
    #[prost(enumeration = "MemoryKind", tag = "4")]
    pub kind: i32,
    #[prost(message, optional, tag = "5")]
    pub content: ::core::option::Option<MemoryContent>,
    #[prost(message, optional, tag = "6")]
    pub signals: ::core::option::Option<MemorySignals>,
    #[prost(message, optional, tag = "7")]
    pub temporal: ::core::option::Option<TemporalMetadata>,
    #[prost(message, optional, tag = "8")]
    pub provenance: ::core::option::Option<Provenance>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextFilter {
    #[prost(string, optional, tag = "1")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub agent_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub run_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TemporalFilter {
    #[prost(int64, optional, tag = "1")]
    pub created_after: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "2")]
    pub created_before: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub updated_after: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "4")]
    pub updated_before: ::core::option::Option<i64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SignalFilter {
    #[prost(float, optional, tag = "1")]
    pub min_certainty: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "2")]
    pub min_salience: ::core::option::Option<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateMemoryRequest {
    #[prost(string, optional, tag = "1")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub agent_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub run_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub raw_content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMemoryRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMemoryRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMemoriesRequest {
    #[prost(message, optional, tag = "1")]
    pub context: ::core::option::Option<ContextFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMemoriesRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub context: ::core::option::Option<ContextFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryResponse {
    #[prost(message, optional, tag = "1")]
    pub memory: ::core::option::Option<Memory>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryListResponse {
    #[prost(message, repeated, tag = "1")]
    pub memories: ::prost::alloc::vec::Vec<Memory>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LifecycleState {
    Unspecified = 0,
    Active = 1,
    Archived = 2,
}
impl LifecycleState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LIFECYCLE_STATE_UNSPECIFIED",
            Self::Active => "LIFECYCLE_STATE_ACTIVE",
            Self::Archived => "LIFECYCLE_STATE_ARCHIVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LIFECYCLE_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "LIFECYCLE_STATE_ACTIVE" => Some(Self::Active),
            "LIFECYCLE_STATE_ARCHIVED" => Some(Self::Archived),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MemoryKind {
    Unspecified = 0,
    Semantic = 1,
    Episodic = 2,
    Procedural = 3,
    Instruction = 4,
    Relational = 5,
    Working = 6,
    Prospective = 7,
}
impl MemoryKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MEMORY_KIND_UNSPECIFIED",
            Self::Semantic => "MEMORY_KIND_SEMANTIC",
            Self::Episodic => "MEMORY_KIND_EPISODIC",
            Self::Procedural => "MEMORY_KIND_PROCEDURAL",
            Self::Instruction => "MEMORY_KIND_INSTRUCTION",
            Self::Relational => "MEMORY_KIND_RELATIONAL",
            Self::Working => "MEMORY_KIND_WORKING",
            Self::Prospective => "MEMORY_KIND_PROSPECTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MEMORY_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "MEMORY_KIND_SEMANTIC" => Some(Self::Semantic),
            "MEMORY_KIND_EPISODIC" => Some(Self::Episodic),
            "MEMORY_KIND_PROCEDURAL" => Some(Self::Procedural),
            "MEMORY_KIND_INSTRUCTION" => Some(Self::Instruction),
            "MEMORY_KIND_RELATIONAL" => Some(Self::Relational),
            "MEMORY_KIND_WORKING" => Some(Self::Working),
            "MEMORY_KIND_PROSPECTIVE" => Some(Self::Prospective),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProvenanceOrigin {
    Unspecified = 0,
    User = 1,
    Agent = 2,
}
impl ProvenanceOrigin {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROVENANCE_ORIGIN_UNSPECIFIED",
            Self::User => "PROVENANCE_ORIGIN_USER",
            Self::Agent => "PROVENANCE_ORIGIN_AGENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROVENANCE_ORIGIN_UNSPECIFIED" => Some(Self::Unspecified),
            "PROVENANCE_ORIGIN_USER" => Some(Self::User),
            "PROVENANCE_ORIGIN_AGENT" => Some(Self::Agent),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod memory_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct MemoryServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MemoryServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MemoryServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MemoryServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MemoryServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_memory(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateMemoryRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/memory_v1.MemoryService/CreateMemory");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("memory_v1.MemoryService", "CreateMemory"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_memory(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteMemoryRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/memory_v1.MemoryService/DeleteMemory");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("memory_v1.MemoryService", "DeleteMemory"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_memory(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMemoryRequest>,
        ) -> std::result::Result<tonic::Response<super::MemoryResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/memory_v1.MemoryService/GetMemory");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("memory_v1.MemoryService", "GetMemory"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_memories(
            &mut self,
            request: impl tonic::IntoRequest<super::ListMemoriesRequest>,
        ) -> std::result::Result<tonic::Response<super::MemoryListResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/memory_v1.MemoryService/ListMemories");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("memory_v1.MemoryService", "ListMemories"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn search_memories(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchMemoriesRequest>,
        ) -> std::result::Result<tonic::Response<super::MemoryListResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/memory_v1.MemoryService/SearchMemories");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("memory_v1.MemoryService", "SearchMemories"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod memory_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MemoryServiceServer.
    #[async_trait]
    pub trait MemoryService: std::marker::Send + std::marker::Sync + 'static {
        async fn create_memory(
            &self,
            request: tonic::Request<super::CreateMemoryRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        async fn delete_memory(
            &self,
            request: tonic::Request<super::DeleteMemoryRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        async fn get_memory(
            &self,
            request: tonic::Request<super::GetMemoryRequest>,
        ) -> std::result::Result<tonic::Response<super::MemoryResponse>, tonic::Status>;
        async fn list_memories(
            &self,
            request: tonic::Request<super::ListMemoriesRequest>,
        ) -> std::result::Result<tonic::Response<super::MemoryListResponse>, tonic::Status>;
        async fn search_memories(
            &self,
            request: tonic::Request<super::SearchMemoriesRequest>,
        ) -> std::result::Result<tonic::Response<super::MemoryListResponse>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct MemoryServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MemoryServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MemoryServiceServer<T>
    where
        T: MemoryService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/memory_v1.MemoryService/CreateMemory" => {
                    #[allow(non_camel_case_types)]
                    struct CreateMemorySvc<T: MemoryService>(pub Arc<T>);
                    impl<T: MemoryService> tonic::server::UnaryService<super::CreateMemoryRequest>
                        for CreateMemorySvc<T>
                    {
                        type Response = ();
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateMemoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MemoryService>::create_memory(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateMemorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/memory_v1.MemoryService/DeleteMemory" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteMemorySvc<T: MemoryService>(pub Arc<T>);
                    impl<T: MemoryService> tonic::server::UnaryService<super::DeleteMemoryRequest>
                        for DeleteMemorySvc<T>
                    {
                        type Response = ();
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteMemoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MemoryService>::delete_memory(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteMemorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/memory_v1.MemoryService/GetMemory" => {
                    #[allow(non_camel_case_types)]
                    struct GetMemorySvc<T: MemoryService>(pub Arc<T>);
                    impl<T: MemoryService> tonic::server::UnaryService<super::GetMemoryRequest> for GetMemorySvc<T> {
                        type Response = super::MemoryResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMemoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MemoryService>::get_memory(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMemorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/memory_v1.MemoryService/ListMemories" => {
                    #[allow(non_camel_case_types)]
                    struct ListMemoriesSvc<T: MemoryService>(pub Arc<T>);
                    impl<T: MemoryService> tonic::server::UnaryService<super::ListMemoriesRequest>
                        for ListMemoriesSvc<T>
                    {
                        type Response = super::MemoryListResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListMemoriesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MemoryService>::list_memories(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListMemoriesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/memory_v1.MemoryService/SearchMemories" => {
                    #[allow(non_camel_case_types)]
                    struct SearchMemoriesSvc<T: MemoryService>(pub Arc<T>);
                    impl<T: MemoryService> tonic::server::UnaryService<super::SearchMemoriesRequest>
                        for SearchMemoriesSvc<T>
                    {
                        type Response = super::MemoryListResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SearchMemoriesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MemoryService>::search_memories(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SearchMemoriesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(empty_body());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for MemoryServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "memory_v1.MemoryService";
    impl<T> tonic::server::NamedService for MemoryServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
